name: example-environment
channels:
  - conda-forge
dependencies:
  - python>=3.6.0
  - numpy
  - plotly
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - pip
  - pip:
      - feather-format
      - julia
      - sos
      - sos-notebook